name: "Create .env File"
description: "A reusable GitHub Action to create a .env file with environment variables."
inputs:
  env-variables:
    description: "A multiline string of environment variables (key=value format)."
    required: true
runs:
  using: "composite"
  steps:
    - name: Create .env file
      shell: bash
      run: |
        echo "${{ inputs.env-variables }}" >> .env
        echo "✅ .env file created successfully"

