name: 👷 Pull request workflow
on:
  pull_request: { branches: "*" }
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  build:
    name: 🏗️ Build project
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🤐 Create .env file
        uses: ./.github/actions/create-env-file
        with:
          env-variables: ${{secrets.SECRETS}}

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 📥 Download deps
        uses: bahmutov/npm-install@7481d8fd7815dc5abfda5f1ec48aa2770e64c318

      - name: 🏗️ Build project (linting + typecheck)
        run: npm run build

  storybook:
    name: 🔬 Storybook - components tests
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🤐 Create .env file
        uses: ./.github/actions/create-env-file
        with:
          env-variables: ${{secrets.SECRETS}}

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 📥 Download deps
        uses: bahmutov/npm-install@7481d8fd7815dc5abfda5f1ec48aa2770e64c318

      - name: 📥 Install Playwright Browsers
        run: npm run test:e2e:install

      - name: 🔬 Run component tests
        run: npm run test:storybook-ci

  e2e:
    name: 🎭 Playwright E2E tests
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🤐 Create .env file
        uses: ./.github/actions/create-env-file
        with:
          env-variables: ${{secrets.SECRETS}}

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 📥 Download deps
        uses: bahmutov/npm-install@7481d8fd7815dc5abfda5f1ec48aa2770e64c318

      - name: 📥 Install Playwright Browsers
        run: npm run test:e2e:install

      - name: 🏗️ Build project
        run: npm run build

      - name: 🎭 Playwright tests
        run: npx playwright test

      - name: 📊 Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
