name: 👷 Pull request workflow
on:
  pull_request: { branches: "*" }
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  build:
    name: 🏗️ Build project
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🏗️ Build project (linting + typecheck)
        run: npm run build
        env:
          NEXT_PUBLIC_GOOGLE_MAP_API_KEY: ${{secrets.NEXT_PUBLIC_GOOGLE_MAP_API_KEY}}
          NEXT_PUBLIC_GOOGLE_MAP_ID: ${{secrets.NEXT_PUBLIC_GOOGLE_MAP_ID}}
          EMAIL_API_URL: ${{secrets.EMAIL_API_URL}}
          EMAIL_SERVICE_ID: ${{secrets.EMAIL_SERVICE_ID}}
          EMAIL_TEMPLATE_ID: ${{secrets.EMAIL_TEMPLATE_ID}}
          EMAIL_PUBLIC_KEY: ${{secrets.EMAIL_PUBLIC_KEY}}
          EMAIL_PRIVATE_KEY: ${{secrets.EMAIL_PRIVATE_KEY}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          NEXT_PUBLIC_SENTRY_DSN: ${{secrets.NEXT_PUBLIC_SENTRY_DSN}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}

  storybook:
    name: 🔬 Storybook - components tests
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 📥 Install Playwright Browsers
        run: npm run test:e2e:install

      - name: 🔬 Run component tests
        run: npm run test:storybook-ci
        env:
          NEXT_PUBLIC_GOOGLE_MAP_API_KEY: ${{secrets.NEXT_PUBLIC_GOOGLE_MAP_API_KEY}}
          NEXT_PUBLIC_GOOGLE_MAP_ID: ${{secrets.NEXT_PUBLIC_GOOGLE_MAP_ID}}
          EMAIL_API_URL: ${{secrets.EMAIL_API_URL}}
          EMAIL_SERVICE_ID: ${{secrets.EMAIL_SERVICE_ID}}
          EMAIL_TEMPLATE_ID: ${{secrets.EMAIL_TEMPLATE_ID}}
          EMAIL_PUBLIC_KEY: ${{secrets.EMAIL_PUBLIC_KEY}}
          EMAIL_PRIVATE_KEY: ${{secrets.EMAIL_PRIVATE_KEY}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          NEXT_PUBLIC_SENTRY_DSN: ${{secrets.NEXT_PUBLIC_SENTRY_DSN}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
