name: 🏗️ Build and Publish Storybook to GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    name: 🚀 Build and Publish Storybook
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🤐 Create .env file
        uses: ./.github/actions/create-env-file
        with:
          env-variables: ${{secrets.SECRETS}}

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 📥 Download deps
        uses: bahmutov/npm-install@ec9e87262db2a1be2ca3ceb2d506c413a220542c

      - name: 🏗️ Build Storybook
        run: npm run build:storybook

      - name: Publish Storybook 🚀
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8
        with:
          folder: storybook-static
